# Generated by Django 4.2.10 on 2024-07-24 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('ssc', 'Matric'), ('hssc', 'F.sc'), ('bs', 'Bachelors'), ('ms', 'Master'), ('phd', 'Doctorate')], default='ssc', help_text="Name of Field in which you have passed bachelors - Leave blank if you don't have bachelors degree", max_length=15)),
                ('experience', models.PositiveIntegerField(default=0, help_text='Years of working experience')),
                ('about', models.TextField(blank=True, help_text='Say something about yourself, your love to hear you, briefly describe yourself, interests etc', null=True)),
                ('previous_company', models.CharField(blank=True, help_text='Leave blank if not', max_length=255, null=True)),
                ('status', models.CharField(choices=[('acc', 'Accepted'), ('pen', 'Pending'), ('app', 'Applied'), ('rej', 'Rejected')], default='app', max_length=3)),
                ('cv', models.FileField(blank=True, null=True, upload_to='company/candidate/cvs/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=255)),
                ('tag_line', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('business_type', models.CharField(choices=[('non profit', 'Non Profit'), ('government', 'Government'), ('small business', 'Small Business'), ('medium business', 'Medium Business'), ('enterprise', 'Enterprise')], default='small business', max_length=255, verbose_name='Company Type')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logo')),
                ('company_registration_no', models.CharField(blank=True, max_length=255, null=True)),
                ('company_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Date started')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('company_address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('vacancy', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('detailed_description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logo')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=5)),
                ('job_type', models.CharField(blank=True, choices=[('full time', 'Full Time'), ('part time', 'Part Time'), ('remote', 'Remote'), ('freelance', 'Freelance'), ('internship', 'Internship')], default='internship', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('candidates', models.ManyToManyField(related_name='candidates', through='company.Candidate', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.city')),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_provider', to='company.company')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.country')),
            ],
            options={
                'verbose_name': 'InternShip',
                'verbose_name_plural': 'InternShips',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', '1 star'), ('2', '2 stars'), ('3', '3 stars'), ('4', '4 stars'), ('5', '5 stars')], default='4', max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='reviews',
            field=models.ManyToManyField(related_name='likes', through='company.Review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='company.job'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
